<a href="https://colab.research.google.com/github/vikrantpotnis123/DS/blob/master/python_basic2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import collections
import numpy as np
x = dict(one=1,two=2)
print(x)

{'one': 1, 'two': 2}


In [ ]:
x.pop('one', 'None')
x

{'two': 2}

In [ ]:
import copy
y = [ 1, 2, [3, 4], 5]
y1 = y.copy()
y[1] = 22

print(y, y1)
y2 = copy.deepcopy(y1)
y[2][1] = 44
print(y, y1, y2, sep='\t', end='\n')

[1, 22, [3, 4], 5] [1, 2, [3, 4], 5]
[1, 22, [3, 44], 5]	[1, 2, [3, 44], 5]	[1, 2, [3, 4], 5]


In [ ]:
import numpy as np
x= np.arange(10).reshape(2,5)
print(x)
y = copy.deepcopy(x)
z = x
x[1][2] = 77
print(x)
print(y)
print(z)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4]
 [ 5  6 77  8  9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4]
 [ 5  6 77  8  9]]


In [ ]:
l = np.array([1, 2, 3, 2, 3])
a, c = np.unique(l,  return_counts=True)
d = {x : y for x, y in zip(a,c)}
d

{1: 1, 2: 2, 3: 2}

In [ ]:
# random list
random = ['a', ('a', 'b'), ('a', 'b'), [3, 4]]

# count element ('a', 'b')
count = random.count(('a', 'b'))

# print count
print("The count of ('a', 'b') is:", count)

The count of ('a', 'b') is: 2


In [ ]:
from collections import Counter
l = np.array([ 1,2, 2, 1, 3, 3, 2, 3, 1])
c = Counter(l)
c

Counter({1: 3, 2: 3, 3: 3})

In [ ]:
c.most_common(2)

[(1, 3), (2, 3)]

In [ ]:
str.lower('DDDDD').capitalize()

'Ddddd'

In [ ]:
list(map(str.upper, [ 'hi', 'there']))

['HI', 'THERE']

In [ ]:
def coo(*args, **kwargs):
  print(type(args), type(kwargs))
  print(f"cooing {args} {kwargs}")
  
  def moo(*args, **kwargs):
    print(f"mooing  {args} {kwargs}")
    return str.upper(str(args)), str.upper(str(kwargs))
  moo(args, kwargs)
  return moo

In [ ]:
x  = coo('hi', 'ho', name='10bombai', age=45)
x('hi', 'ho', name='10bombai', age=45)

<class 'tuple'> <class 'dict'>
cooing ('hi', 'ho') {'name': '10bombai', 'age': 45}
mooing  (('hi', 'ho'), {'name': '10bombai', 'age': 45}) {}
mooing  ('hi', 'ho') {'name': '10bombai', 'age': 45}


("('HI', 'HO')", "{'NAME': '10BOMBAI', 'AGE': 45}")

In [ ]:
def coo2(*args, **kwargs):
  print(f"cooing2  {args} {kwargs}")
  def moo2(*args, **kwargs):
    print(f"mooing2  {args} {kwargs}")
    return str.upper(str(args)), str.upper(str(kwargs))
  return moo2

In [ ]:
z = coo2('hello', name='gunga din')
z('popatal', name='popat')

cooing2  ('hello',) {'name': 'gunga din'}
mooing2  ('popatal',) {'name': 'popat'}


("('POPATAL',)", "{'NAME': 'POPAT'}")

In [ ]:
class MyEmployee:
  def __init__(self, name, age):
    self._name = name
    self._age = age
  
  @property
  def name(self):
    print("getter called!")
    return self._name

  @name.setter
  def name(self, newname):
    print("setter called!")
    self._name = newname

  @name.deleter
  def name(self):
    print("deleter called!")
    del self._name

In [ ]:
e = MyEmployee("Tina", 33)
e.name = "Tina M"
print(e.name)
del e.name

setter called!
getter called!
Tina M
deleter called!


In [ ]:
from collections import defaultdict
import numpy as np
print(issubclass(defaultdict, dict))
students = [ "popat", "locha", "mynah", "tina"]
sem1_scores =  np.array([65, 50, 75, 85], dtype=np.int32)
sem2_scores =  np.array([55, 80, 75, 65], dtype=np.int32)
d = defaultdict(list)
for x, y1, y2 in zip(students, sem1_scores, sem2_scores):
  d[x].append(y1)
  d[x].append(y2)
print(d.items())


True
dict_items([('popat', [65, 55]), ('locha', [50, 80]), ('mynah', [75, 75]), ('tina', [85, 65])])


In [ ]:
from abc import ABC, abstractmethod

class MLModel(ABC):
  def __init__(self, pipeline_config):
    self.pipeline_config = pipeline_config

  @abstractmethod
  def predict(self, test_data):
    pass

  @abstractmethod
  def train(self, train_data):
    pass

class SSDModel(MLModel):
  
  def __init__(self, pipeline_config):
    super().__init__(pipeline_config)

  def predict(self, test_data):
    print (f"SSD model predict {test_data}")

  def train(self, train_data):
    print (f"SSD model train {train_data}")

In [ ]:
train_data = "blah blah"
test_data = "bloo bloo"
pipeline_config = "mypipeline.cfg"
m = SSDModel(pipeline_config)
m.train(train_data)
m.predict(test_data)

SSD model train blah blah
SSD model predict bloo bloo


In [ ]:
import logging
import time
import numpy as np
class MyLogger:
  import logging
  def __init__(self, func):
    self.func = func
    print(f"constructing {type(self).__name__} with {self.func.__name__}")

  def __call__(self, *args, **kwargs):
    start_time = time.time()
    r = self.func(self, args, kwargs)
    print(f"MyTP(): {self.func.__name__} {args} {kwargs}")
    print(f"  took {time.time()-start_time} seconds to execute!")
    return r

class MyTP:
  def __init__(self, *args, **kwargs):
    print(f"constructing {type(self).__name__}")
    self.args = args
    self.kwargs = kwargs

  @MyLogger
  def __call__(self, *args, **kwargs):
    print(f"Executing MyTP : __call__ {args}, {kwargs}")

constructing MyLogger with __call__


In [ ]:
t = MyTP("hi", time='pass', mynah=3, satveh='chichichi')
t("hi", time='pass', mynah=3, satveh='chichichi')

constructing MyTP
Executing MyTP : __call__ (('hi',), {'time': 'pass', 'mynah': 3, 'satveh': 'chichichi'}), {}
MyTP(): __call__ ('hi',) {'time': 'pass', 'mynah': 3, 'satveh': 'chichichi'}
  took 0.0009016990661621094 seconds to execute!


In [ ]:
import functools as f

In [ ]:
%time f.reduce(lambda x, y : max(x, y), [1, 2, 3, 4, 5])

CPU times: user 7 µs, sys: 2 µs, total: 9 µs
Wall time: 11.2 µs


5

## Profiling decorator

In [ ]:
import cProfile, pstats, io
import numpy as np
class MyProfiler:
  def __init__(self,func):
    self.func = func
    self.pr = cProfile.Profile();
    self.s = io.StringIO()
  
  def __call__(self, *args, **kwargs):
    self.pr.enable()
    ret = self.func(*args, **kwargs)
    self.pr.disable()
    self.ps = pstats.Stats(self.pr, stream=self.s).sort_stats('cumulative')
    self.ps.print_stats()
    print(self.s.getvalue())
    return ret


In [ ]:
@MyProfiler
def profiling_test1(n): 
  iterable = (i**2 for i in range(n))
  x =  np.fromiter(iterable, dtype=np.int32)

@MyProfiler
def profiling_test2(n): 
  y =  [x**2 for x in range(n)]

profiling_test1(100000)
profiling_test2(100000)

         100004 function calls in 0.045 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.045    0.045 <ipython-input-13-24ad2a6f4e9c>:1(profiling_test1)
        1    0.013    0.013    0.045    0.045 {built-in method numpy.fromiter}
   100001    0.032    0.000    0.032    0.000 <ipython-input-13-24ad2a6f4e9c>:3(<genexpr>)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}



         3 function calls in 0.029 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.029    0.029 <ipython-input-13-24ad2a6f4e9c>:6(profiling_test2)
        1    0.029    0.029    0.029    0.029 <ipython-input-13-24ad2a6f4e9c>:8(<listcomp>)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}





In [ ]:
iterable = [x*x for x in range(5)]
print(type(iterable))

<class 'list'>


In [ ]:
class chunker:
  def __init__(self, lst, n):
    self.lst = lst
    self.n = n

  def __iter__(self):
    """Yield successive n-sized chunks from lst."""
    for i in range(0, len(self.lst), self.n):
      print(i)
      yield self.lst[i : i+self.n]

In [ ]:
from google.colab import drive

drive.mount('/content/gdrive')


Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
%cat gdrive/MyDrive/wine.csv

Wine,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
1,14.23,1.71,2.43,15.6,127,2.8,3.06,.28,2.29,5.64,1.04,3.92,1065
1,13.2,1.78,2.14,11.2,100,2.65,2.76,.26,1.28,4.38,1.05,3.4,1050
1,13.16,2.36,2.67,18.6,101,2.8,3.24,.3,2.81,5.68,1.03,3.17,1185
1,14.37,1.95,2.5,16.8,113,3.85,3.49,.24,2.18,7.8,.86,3.45,1480
1,13.24,2.59,2.87,21,118,2.8,2.69,.39,1.82,4.32,1.04,2.93,735
1,14.2,1.76,2.45,15.2,112,3.27,3.39,.34,1.97,6.75,1.05,2.85,1450
1,14.39,1.87,2.45,14.6,96,2.5,2.52,.3,1.98,5.25,1.02,3.58,1290
1,14.06,2.15,2.61,17.6,121,2.6,2.51,.31,1.25,5.05,1.06,3.58,1295
1,14.83,1.64,2.17,14,97,2.8,2.98,.29,1.98,5.2,1.08,2.85,1045
1,13.86,1.35,2.27,16,98,2.98,3.15,.22,1.85,7.22,1.01,3.55,1045
1,14.1,2.16,2.3,18,105,2.95,3.32,.22,2.38,5.75,1.25,3.17,1510
1,14.12,1.48,2.32,16.8,95,2.2,2.43,.26,1.57,5,1.17,2.82,1280
1,13.75,1.73,2.41,16,89,2.6,2.76,.29,1.81,5.6,1.15,2.9,1320
1,14.75,1.73,2.39,11.4,91,3.1,3.69,.43,2.81,5.4,1.25,2.73,1150
1,14.38,1.8

In [ ]:
import numpy as np

l = iter(np.array([1,2,3]))
l1 = iter([4, 5, 6])
print(next(l))
print(next(l))
print(next(l1))
print(next(l1))

1
2
4
5


In [ ]:
lines = []
with open('gdrive/MyDrive/wine.csv') as f:
  lines = f.read().splitlines()


lines

['Wine,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline',
 '1,14.23,1.71,2.43,15.6,127,2.8,3.06,.28,2.29,5.64,1.04,3.92,1065',
 '1,13.2,1.78,2.14,11.2,100,2.65,2.76,.26,1.28,4.38,1.05,3.4,1050',
 '1,13.16,2.36,2.67,18.6,101,2.8,3.24,.3,2.81,5.68,1.03,3.17,1185',
 '1,14.37,1.95,2.5,16.8,113,3.85,3.49,.24,2.18,7.8,.86,3.45,1480',
 '1,13.24,2.59,2.87,21,118,2.8,2.69,.39,1.82,4.32,1.04,2.93,735',
 '1,14.2,1.76,2.45,15.2,112,3.27,3.39,.34,1.97,6.75,1.05,2.85,1450',
 '1,14.39,1.87,2.45,14.6,96,2.5,2.52,.3,1.98,5.25,1.02,3.58,1290',
 '1,14.06,2.15,2.61,17.6,121,2.6,2.51,.31,1.25,5.05,1.06,3.58,1295',
 '1,14.83,1.64,2.17,14,97,2.8,2.98,.29,1.98,5.2,1.08,2.85,1045',
 '1,13.86,1.35,2.27,16,98,2.98,3.15,.22,1.85,7.22,1.01,3.55,1045',
 '1,14.1,2.16,2.3,18,105,2.95,3.32,.22,2.38,5.75,1.25,3.17,1510',
 '1,14.12,1.48,2.32,16.8,95,2.2,2.43,.26,1.57,5,1.17,2.82,1280',
 '1,13.75,1.73,2.41,16,89,2.6,2.76,.29,1.81,5.6,1.15,2.9,1320',
 '1,14.75,1.73,2.3

In [ ]:
c = iter(chunker(lines, 5))
while True:
  try:
    print(next(c))
  except StopIteration:
    break
del c

0
['Wine,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline', '1,14.23,1.71,2.43,15.6,127,2.8,3.06,.28,2.29,5.64,1.04,3.92,1065', '1,13.2,1.78,2.14,11.2,100,2.65,2.76,.26,1.28,4.38,1.05,3.4,1050', '1,13.16,2.36,2.67,18.6,101,2.8,3.24,.3,2.81,5.68,1.03,3.17,1185', '1,14.37,1.95,2.5,16.8,113,3.85,3.49,.24,2.18,7.8,.86,3.45,1480']
5
['1,13.24,2.59,2.87,21,118,2.8,2.69,.39,1.82,4.32,1.04,2.93,735', '1,14.2,1.76,2.45,15.2,112,3.27,3.39,.34,1.97,6.75,1.05,2.85,1450', '1,14.39,1.87,2.45,14.6,96,2.5,2.52,.3,1.98,5.25,1.02,3.58,1290', '1,14.06,2.15,2.61,17.6,121,2.6,2.51,.31,1.25,5.05,1.06,3.58,1295', '1,14.83,1.64,2.17,14,97,2.8,2.98,.29,1.98,5.2,1.08,2.85,1045']
10
['1,13.86,1.35,2.27,16,98,2.98,3.15,.22,1.85,7.22,1.01,3.55,1045', '1,14.1,2.16,2.3,18,105,2.95,3.32,.22,2.38,5.75,1.25,3.17,1510', '1,14.12,1.48,2.32,16.8,95,2.2,2.43,.26,1.57,5,1.17,2.82,1280', '1,13.75,1.73,2.41,16,89,2.6,2.76,.29,1.81,5.6,1.15,2.9,1320', '1,14.75,1.73,2.39,11.

In [ ]:
import random
import pdb
def code_to_debug():  
  pdb.set_trace()
  for i in range(100):
    x = random.random()
    print(x)

In [ ]:
code_to_debug()

> <ipython-input-21-6cadee9054d4>(5)code_to_debug()
-> for i in range(100):
(Pdb) c
0.14713134499024128
0.462197901640405
0.8586736881886449
0.6396828943441247
0.9726819020053856
0.3754032566268577
0.846562428064602
0.04028579212725292
0.9349967592496841
0.5391342146816128
0.63810486661286
0.9558326678851063
0.37519353072398565
0.24042952065262946
0.11679863078683528
0.7597872722207866
0.34557698744593635
0.3387581676136241
0.9509434137641867
0.655932810074845
0.7189019218322938
0.9978265279331167
0.8083806285510027
0.8671706511079516
0.15453007991820245
0.1942346590775762
0.8972065138276956
0.02648096096648822
0.7224080393177569
0.6711787055175312
0.47731891973732554
0.808574724514478
0.7277020526090108
0.892819201666698
0.8374565791550705
0.19133595054785957
0.794532909211295
0.6358189127914217
0.8214016910365053
0.7678280272490846
0.054459133622868916
0.7061598573678843
0.1742337935371917
0.06330536450150637
0.29839999638284875
0.5325841402610137
0.9226940305970169
0.152833862512849

In [ ]:
from itertools import chain

In [ ]:
list(chain.from_iterable((i, i**2) for i in range(1, 6)))

[1, 1, 2, 4, 3, 9, 4, 16, 5, 25]

In [ ]:
                                                                          k = [ "k1", "k2", "k3"]
d = { "k1" : "f1", "k2" : "f2" }
list(chain.from_iterable((k, d[k]) for k in d))


['k1', 'f1', 'k2', 'f2']

In [ ]:
import operator
import numpy as np

l1 = np.full(10, 3)
l2 = np.full(1000, 4.5)
#print(l1, l2)

r1 = map(operator.mul, l1, l2)
r1 = np.fromiter(r1, dtype=np.float32)
print(r1)

r2 = map(lambda x, y : x*y , l1, l2)
r2 = np.fromiter(r2, dtype=np.float32)
print(r2)

l3 = [ "This", "sucks!"]
l4 = [ y for x in l3 for y in x ]
print(l4)


[13.5 13.5 13.5 13.5 13.5 13.5 13.5 13.5 13.5 13.5]
[13.5 13.5 13.5 13.5 13.5 13.5 13.5 13.5 13.5 13.5]


['T', 'h', 'i', 's', 's', 'u', 'c', 'k', 's', '!']

In [ ]:
import numpy as np
n1 = np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
from collections import Counter
c = Counter()
r1 = Counter([1, 1, 2, 1, 2])
r1 = r1.elements()
r1 = np.fromiter(r1, dtype=np.float32)
print(r1)
r2 = list(Counter(cats=2, dogs=4, elephants=6, kangaroos=3).values())
print(r2)
print(r2[:-3:-1])
r2 = Counter(cats=2, dogs=4, elephants=6, kangaroos=3).most_common(2)
print(r2)
r3 = Counter({1:2, 3:2, 4:50, 6:1})
r3.most_common()


[1. 1. 1. 2. 2.]
[2, 4, 6, 3]
[3, 6]
[('elephants', 6), ('dogs', 4)]


[(4, 50), (1, 2), (3, 2), (6, 1)]

In [2]:
def my_sum(a, b, c, d):
  return a+b+c+d

In [3]:
l = [ 1, 2, 3, 4]
print(my_sum(*l))

10


In [4]:
l = [1, 2]
d = { 'c': 3, 'd' : 4}
print(my_sum(*l, **d))

10


In [19]:
l = [1, 2, 3, 4]
i1  = iter(l)
x = zip(i1, i1)
y = zip(l, l)
print(list(x))
print(list(y))

[(1, 2), (3, 4)]
[(1, 1), (2, 2), (3, 3), (4, 4)]


In [10]:
def better_grouper(inputs, n):
    iters = [iter(inputs)] * n
    print(list(iters))
    return zip(*iters)

In [13]:
inputs = [1, 2, 3, 4, 5, 6]
z = better_grouper(inputs, 2)
print(list(z))

[<list_iterator object at 0x7ff82bb46950>, <list_iterator object at 0x7ff82bb46950>]
[(1, 2), (3, 4), (5, 6)]
