<a href="https://colab.research.google.com/github/vikrantpotnis123/DS/blob/master/python_basic2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import collections
x = dict(one=1,two=2)
print(x)

{'one': 1, 'two': 2}


In [ ]:
x.pop('one', 'None')
x

{'two': 2}

In [ ]:
import copy
y = [ 1, 2, [3, 4], 5]
y1 = y.copy()
y[1] = 22

print(y, y1)
y2 = copy.deepcopy(y1)
y[2][1] = 44
print(y, y1, y2, sep='\t', end='\n')

[1, 22, [3, 4], 5] [1, 2, [3, 4], 5]
[1, 22, [3, 44], 5]	[1, 2, [3, 44], 5]	[1, 2, [3, 4], 5]


In [ ]:
import numpy as np
x= np.arange(10).reshape(2,5)
print(x)
y = copy.deepcopy(x)
z = x
x[1][2] = 77
print(x)
print(y)
print(z)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4]
 [ 5  6 77  8  9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4]
 [ 5  6 77  8  9]]


In [ ]:
l = [1, 2, 3, 2, 3]
l.count(2)

2

In [ ]:
# random list
random = ['a', ('a', 'b'), ('a', 'b'), [3, 4]]

# count element ('a', 'b')
count = random.count(('a', 'b'))

# print count
print("The count of ('a', 'b') is:", count)

The count of ('a', 'b') is: 2


In [ ]:
from collections import Counter
l = [ 1,2, 2, 1, 3, 3, 2, 3, 1]
c = Counter(l)
c

Counter({1: 3, 2: 3, 3: 3})

In [ ]:
c.most_common(2)

[(1, 3), (2, 3)]

In [ ]:
f'hello, {name}, gunga din'

'hello, bob cat, gunga din'

In [ ]:
str.lower('DDDDD').capitalize()

'Ddddd'

In [ ]:
list(map(str.upper, [ 'hi', 'there']))

['HI', 'THERE']

In [ ]:
def coo(*args, **kwargs):
  print(type(args), type(kwargs))
  print(f"cooing {args} {kwargs}")
  
  def moo(*args, **kwargs):
    print(f"mooing  {args} {kwargs}")
    return str.upper(str(args)), str.upper(str(kwargs))
  moo(args, kwargs)
  return moo

In [ ]:
x  = coo('hi', 'ho', name='10bombai', age=45)
x('hi', 'ho', name='10bombai', age=45)

<class 'tuple'> <class 'dict'>
cooing ('hi', 'ho') {'name': '10bombai', 'age': 45}
mooing  (('hi', 'ho'), {'name': '10bombai', 'age': 45}) {}
mooing  ('hi', 'ho') {'name': '10bombai', 'age': 45}


("('HI', 'HO')", "{'NAME': '10BOMBAI', 'AGE': 45}")

In [ ]:
def coo2(*args, **kwargs):
  print(f"cooing2  {args} {kwargs}")
  def moo2(*args, **kwargs):
    print(f"mooing2  {args} {kwargs}")
    return str.upper(str(args)), str.upper(str(kwargs))
  return moo2

In [ ]:
z = coo2('hello', name='gunga din')
z('popatal', name='popat')

cooing2  ('hello',) {'name': 'gunga din'}
mooing2  ('popatal',) {'name': 'popat'}


("('POPATAL',)", "{'NAME': 'POPAT'}")

In [ ]:
class MyEmployee:
  def __init__(self, name, age):
    self._name = name
    self._age = age
  
  @property
  def name(self):
    print("getter called!")
    return self._name

  @name.setter
  def name(self, newname):
    print("setter called!")
    self._name = newname

  @name.deleter
  def name(self):
    print("deleter called!")
    del self._name

In [ ]:
e = MyEmployee("Tina", 33)
e.name = "Tina M"
print(e.name)
del e.name

setter called!
getter called!
Tina M
deleter called!


In [21]:
from collections import defaultdict
print(issubclass(defaultdict, dict))
students = [ "popat", "locha", "mynah", "tina"]
sem1_scores =  [65, 50, 75, 85]
sem2_scores =  [55, 80, 75, 65]
d = defaultdict(list)
for x, y1, y2 in zip(students, sem1_scores, sem2_scores):
  d[x].append(y1)
  d[x].append(y2)
print(d.items())


True
dict_items([('popat', [65, 55]), ('locha', [50, 80]), ('mynah', [75, 75]), ('tina', [85, 65])])


In [12]:
from abc import ABC, abstractmethod

class MLModel(ABC):
  def __init__(self, pipeline_config):
    self.pipeline_config = pipeline_config

  @abstractmethod
  def predict(self, test_data):
    pass

  @abstractmethod
  def train(self, train_data):
    pass

class SSDModel(MLModel):
  
  def __init__(self, pipeline_config):
    super().__init__(pipeline_config)

  def predict(self, test_data):
    print (f"SSD model predict {test_data}")

  def train(self, train_data):
    print (f"SSD model train {train_data}")

In [13]:
train_data = "blah blah"
test_data = "bloo bloo"
pipeline_config = "mypipeline.cfg"
m = SSDModel(pipeline_config)
m.train(train_data)
m.predict(test_data)

SSD model train blah blah
SSD model predict bloo bloo
