<a href="https://colab.research.google.com/github/vikrantpotnis123/DS/blob/master/tf_keras_basic_img_classify_with_conv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

'''
create a training and test data sets
fashion mnist has 70k grayscale 28x28 images in 10 categories
60k are used to train and 10k are used to test
'''
mnist = tf.keras.datasets.fashion_mnist
(training_images, training_labels),(test_images, test_labels) = mnist.load_data()
training_images, test_images = training_images / 255.0, test_images / 255.0
training_images = tf.expand_dims(training_images,axis=3)
test_images = tf.expand_dims(test_images,axis=3)


2.4.0


In [2]:
print(training_images.shape)
training_labels

(60000, 28, 28, 1)


array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [4]:
class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs={}):
    if(logs.get('accuracy')> 0.91):
      print("\nReached 91% accuracy so cancelling training!")
      self.model.stop_training = True

# build model
'''
model = tf.keras.Sequential([
                             
                             tf.keras.layers.Flatten(input_shape=(28,28, 1)),
                             tf.keras.layers.Dense(128, activation=tf.nn.relu),
                             tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
'''

model = tf.keras.models.Sequential([
      # convolution layers
      tf.keras.layers.Conv2D(64, (3,3), activation='relu', input_shape=(28, 28,1)),
      tf.keras.layers.MaxPooling2D(2, 2),
      tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
      tf.keras.layers.MaxPooling2D(2,2),
      
      # tf.keras.layers.Flatten(input_shape=(28,28)),
      tf.keras.layers.Flatten(),
      tf.keras.layers.Dense(128, activation=tf.nn.relu),
      tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])

model.summary()

# compile model
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy', 
              metrics=['accuracy'])

# train model
callbacks = myCallback()
model.fit(training_images, training_labels, epochs=10, callbacks=[callbacks])


Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_2 (Conv2D)            (None, 26, 26, 64)        640       
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 13, 13, 64)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 11, 11, 64)        36928     
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 5, 5, 64)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 1600)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 128)               204928    
_________________________________________________________________
dense_3 (Dense)              (None, 10)               

In [5]:
# eval model
test_loss, test_acc  = model.evaluate(test_images, test_labels, verbose=2)
print('\nTest accuracy:', test_acc)

313/313 - 1s - loss: 0.2554 - accuracy: 0.9086

Test accuracy: 0.9085999727249146


In [6]:
# make predictions

In [7]:
predictions = model.predict(test_images)
predictions[0]

array([9.9796047e-08, 4.9783548e-06, 1.2830061e-07, 5.4294384e-07,
       1.7045206e-08, 1.8496823e-04, 3.8561075e-07, 3.0915081e-04,
       2.3083474e-07, 9.9949944e-01], dtype=float32)

In [8]:
predictions[1]

array([6.2046900e-05, 1.5149945e-08, 9.9895263e-01, 1.2522771e-07,
       9.7980537e-04, 2.2551620e-12, 5.3641916e-06, 3.3009455e-12,
       1.5061107e-10, 2.1165576e-12], dtype=float32)