<a href="https://colab.research.google.com/github/vikrantpotnis123/DS/blob/master/tf_keras_basic_img_classify.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from __future__ import print_function

%tensorflow_version 1.x
import tensorflow as tf
print(tf.__version__)

# Create a graph.
g = tf.Graph()

# Establish the graph as the "default" graph.
with g.as_default():
  # Assemble a graph consisting of the following three operations:
  #   * Two tf.constant operations to create the operands.
  #   * One tf.add operation to add the two operands.
  x = tf.constant(8, name="x_const")
  y = tf.constant(5, name="y_const")
  my_sum = tf.add(x, y, name="x_y_sum")


  # Now create a session.
  # The session will run the default graph.
  with tf.Session() as sess:
    print(my_sum.eval())

1.15.2
13


In [ ]:
%tensorflow_version 1.x
import tensorflow as tf
print(tf.__version__)

'''
create a training and test data sets
fashion mnist has 70k grayscale 28x28 images in 10 categories
60k are used to train and 10k are used to test
'''
mnist = tf.keras.datasets.fashion_mnist
(training_images, training_labels),(test_images, test_labels) = mnist.load_data()
training_images, test_images = training_images / 255.0, test_images / 255.0


1.15.2
4423680/4422102 [==============================] - 0s 0us/step
(60000, 28, 28)


In [ ]:
print(training_images.shape)
training_labels

(60000, 28, 28)


array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [ ]:
class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs={}):
    if(logs.get('acc')> 0.91):
      print("\nReached 91% accuracy so cancelling training!")
      self.model.stop_training = True

# build model
model = tf.keras.Sequential([
                             tf.keras.layers.Flatten(input_shape=(28,28)),
                             tf.keras.layers.Dense(128, activation=tf.nn.relu),
                             tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])

# compile model
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy', 
              metrics=['accuracy'])

# train model
callbacks = myCallback()
model.fit(training_images, training_labels, epochs=10, callbacks=[callbacks])


Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 5s 77us/sample - loss: 0.4953 - acc: 0.8247
Epoch 2/10
60000/60000 [==============================] - 5s 76us/sample - loss: 0.3726 - acc: 0.8653
Epoch 3/10
60000/60000 [==============================] - 4s 74us/sample - loss: 0.3330 - acc: 0.8783
Epoch 4/10
60000/60000 [==============================] - 5s 75us/sample - loss: 0.3086 - acc: 0.8866
Epoch 5/10
60000/60000 [==============================] - 5s 75us/sample - loss: 0.2913 - acc: 0.8921
Epoch 6/10
60000/60000 [==============================] - 4s 72us/sample - loss: 0.2774 - acc: 0.8965
Epoch 7/10
60000/60000 [==============================] - 4s 73us/sample - loss: 0.2631 - acc: 0.9020
Epoch 8/10
60000/60000 [==============================] - 4s 72us/sample - loss: 0.2543 - acc: 0.9052
Epoch 9/10
60000/60000 [==============================] - 4s 71us/sample - loss: 0.2449 - acc: 0.9077
Epoch 10/10
59680/60000 [============================>.] - 

In [ ]:
# eval model
test_loss, test_acc  = model.evaluate(test_images, test_labels, verbose=2)
print('\nTest accuracy:', test_acc)

10000/10000 - 0s - loss: 0.3325 - acc: 0.8878

Test accuracy: 0.8878


In [ ]:
# make predictions

In [ ]:
predictions = model.predict(test_images)
predictions[0]

array([3.9443108e-08, 1.4466038e-12, 1.1909810e-09, 1.4583348e-10,
       7.8696816e-10, 1.6486205e-04, 3.3465547e-08, 2.1509810e-03,
       6.8254121e-07, 9.9768341e-01], dtype=float32)

In [ ]:
predictions[1]

array([4.6317198e-04, 4.7740623e-14, 9.9880564e-01, 6.3396207e-13,
       4.6893928e-04, 3.7262792e-14, 2.6229332e-04, 2.5738821e-21,
       1.5231372e-10, 3.3571645e-15], dtype=float32)